# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='aesthetic_pref',
            new_name='has_aesthetic_feedback_goal',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='transportation_pref',
            new_name='has_transportation_feedback_goal',
        ),
    ]
