# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20160911_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='has_aesthetic_feedback_goal',
        ),
        migrations.RemoveField(
            model_name='project',
            name='has_transportation_feedback_goal',
        ),
    ]
