# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20160912_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feedback_goals',
            field=models.ManyToManyField(to='survey.FeedbackGoal'),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
