# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 03:36
from __future__ import unicode_literals

from django.db import migrations

def create_goals(apps, schema_editor):
    
    FeedbackGoal = apps.get_model("survey", "FeedbackGoal")

    FeedbackGoal.objects.all().delete()
    
    aesthetics = FeedbackGoal()
    aesthetics.name = "Aesthetics"
    aesthetics.description = "Obtain aesthetic preferences: Selecting this option will cause relevant survey questions to be displayed"
    aesthetics.save()

    transportation = FeedbackGoal()
    transportation.name = "Transportation"
    transportation.description = "Obtain transportation preferences: Selecting this option will cause relevant survey questions to be displayed"
    transportation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20160912_0538'),
    ]

    operations = [
    	migrations.RunPython(create_goals),
    ]