# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 03:55
from __future__ import unicode_literals

from django.db import migrations

def create_questions(apps, schema_editor):
    
    TMCQ = apps.get_model("survey", "TMCQ")

    #TMCQ.objects.all().delete()
    aesthetics = FeedbackGoal.objects.filter(name = "Aesthetics")
    transportation = FeedbackGoal.objects.filter(name = "Transportation")

    question1 = TMCQ()
    question1.feedback_goal = aesthetics
    question1.question_text = "Is David a good boss"
    question1.option1 = "No"
    question1.option2 = "Hell No"
    question1.option3 = "Are you kidding me?"
    question1.option4 = ""
    question1.option5 = ""

    question1.save()

    question2 = TMCQ()
    question2.feedback_goal = aesthetics
    question2.question_text = "Is Erika a good employee"
    question2.option1 = "Yes"
    question2.option2 = "Hell Yes"
    question2.option3 = "Are you kidding me?"
    question2.option4 = ""
    question2.option5 = ""

    question2.save()

	question3 = TMCQ()
    question3.feedback_goal = transportation
    question3.question_text = "Who is better looking"
    question3.option1 = "Adam"
    question3.option2 = "David"
    question3.option3 = "Are you kidding me?"
    question3.option4 = "Adammmmmmm"
    question3.option5 = "This is not a question"

    question3.save()

class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20160915_0348'),
    ]

    operations = [
    	migrations.RunPython(create_questions),
    ]
