# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-03 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20160915_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='polygon_coords',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
